# Generated by Django 3.1.7 on 2021-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0005_auto_20210319_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbq',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farsi',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
