# Generated by Django 3.1.7 on 2021-03-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0006_auto_20210319_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dakhal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dash.bread')),
            ],
        ),
    ]
