# Generated by Django 3.1.7 on 2021-03-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0007_dakhal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbq',
            options={'verbose_name_plural': 'BBQ'},
        ),
        migrations.AlterModelOptions(
            name='bread',
            options={'verbose_name_plural': 'Bread'},
        ),
        migrations.AlterModelOptions(
            name='dakhal',
            options={'verbose_name_plural': 'Dakhal'},
        ),
        migrations.AlterModelOptions(
            name='farsi',
            options={'verbose_name_plural': 'Farsi'},
        ),
        migrations.CreateModel(
            name='Siraj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dash.bread')),
            ],
            options={
                'verbose_name_plural': 'Siraj',
            },
        ),
    ]
