# Generated by Django 3.1.7 on 2021-03-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0008_auto_20210319_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('Unit_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('totol_price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
