# Generated by Django 3.1.7 on 2021-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0009_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('Liter', 'Liter'), ('Gallon', ' Gallon'), ('Package', 'Package')], max_length=150, null=True),
        ),
    ]
