# Generated by Django 3.1.7 on 2021-03-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dash', '0016_expenses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_expenses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Piece', 'Piece'), ('KG', 'KG'), ('Liter', 'Liter'), ('Gallon', ' Gallon'), ('Package', 'Package')], default='Piece', max_length=150, null=True),
        ),
    ]
