# Generated by Django 3.1.7 on 2021-03-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0021_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='upload_location', verbose_name='Upload a square picture of yourself.'),
        ),
    ]
